# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 79e88f03b23722a31d1c847aeff0446f424e972cdcbb602a7b7b0dc0c5e50c8088674eec431d7de7432e418fc7a78a1a228493fd173765c7e66dff6b15b366bd

test:
  secret_key_base: d037b4b0c900fc82df3f911497c7d75f11a6e8c0b7a34358e1c7674de9011beccb3ba5cc1929c35981c51685adac94a8b62139460230763b919fa3ac98671d75

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
